export const ENV_KEYS = {
  NODE_ENV: 'NODE_ENV',
  APP_PORT: 'APP_PORT',
  LOG_LEVEL: 'LOG_LEVEL',
  DATABASE_URL: 'DATABASE_URL',
  POSTGRES_DB: 'POSTGRES_DB',
  POSTGRES_USER: 'POSTGRES_USER',
  POSTGRES_PASSWORD: 'POSTGRES_PASSWORD',
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
  SCHEDULER_CRON: 'SCHEDULER_CRON',
  SCHEDULER_BATCH_SIZE: 'SCHEDULER_BATCH_SIZE',
  ACTIVITY_MAX_PERIOD_DAYS: 'ACTIVITY_MAX_PERIOD_DAYS',
} as const;

export type EnvKey = (typeof ENV_KEYS)[keyof typeof ENV_KEYS];
